export const KNOWN_PROFILE_FIELDS = [
  'id',
  'hid',
  'father_id',
  'mother_id',
  'generation',
  'sibling_order',
  'name',
  'kunya',
  'nickname',
  'gender',
  'status',
  'dob_data',
  'dod_data',
  'bio',
  'biography',
  'birth_place',
  'current_residence',
  'occupation',
  'education',
  'phone',
  'email',
  'photo_url',
  'social_media_links',
  'achievements',
  'timeline',
  'dob_is_public',
  'profile_visibility',
  'created_by',
  'updated_by',
  'created_at',
  'updated_at',
  'descendants_count',
  'tree_meta',
  'role',
  'user_id',
  'family_origin',
  'version',
  'deleted_at',
  'search_vector',
  'layout_position',
];

export const VIEW_TABS = [
  { id: 'general', label: 'عام' },
  { id: 'details', label: 'تفاصيل' },
  { id: 'family', label: 'العائلة' },
  { id: 'contact', label: 'التواصل' },
];

export const PERMISSION_LEVELS = {
  DIRECT: ['admin', 'moderator', 'inner'],
  REVIEW: ['family', 'extended'],
};
