-- Migration: Add photo_url_cropped for file-based crop storage
-- Author: Claude Code
-- Date: 2025-01-31
-- Purpose: Store cropped image variant URL for non-destructive cropping
-- Approach: File-based (not coordinate-based) for simplicity and performance

-- ============================================================================
-- SCHEMA: Add photo_url_cropped column
-- ============================================================================

ALTER TABLE profiles ADD COLUMN photo_url_cropped TEXT;

COMMENT ON COLUMN profiles.photo_url_cropped IS
  'URL to cropped photo variant (optional).
  When set, UI displays this instead of photo_url.
  Original photo_url preserved for re-cropping (non-destructive).
  Generated by PhotoCropEditor component after user crops photo.
  Added 2025-01-31 to replace coordinate-based cropping.';

-- ============================================================================
-- NOTE: RPC Updates
-- ============================================================================
-- Multiple overloaded versions of get_structure_only() exist in the database.
-- We'll update the RPC functions in a separate migration after determining
-- which signature is actively used by the codebase.
--
-- For now, components will query profiles table directly:
-- SELECT id, photo_url, photo_url_cropped FROM profiles WHERE ...
--
-- Future migration will add photo_url_cropped to all get_structure_only() variants.

-- ============================================================================
-- VERIFICATION
-- ============================================================================

-- Verify column exists:
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'profiles' AND column_name = 'photo_url_cropped';
--
-- Expected: photo_url_cropped | text | YES
